# Generated by Django 5.1.4 on 2025-01-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_discount_amount_product_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_amount',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
